"use client"

import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Provider } from 'react-redux'; // Import Redux Provider
import { store } from './store'; // Import your Redux store
import { Toaster } from "@/components/ui/toaster";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <Provider store={store}> {/* Wrap with Redux Provider */}
            {children}
        </Provider>
        <Toaster />
      </body>
    </html>
  );
}
